import assert from 'node:assert/strict';
import {access} from 'node:fs/promises';

const expected = [
  'Accordion',
  'ActionMenu',
  'AdaptiveSheet',
  'AlertDialog',
  'Avatar',
  'Badge',
  'BreadcrumbTrail',
  'Button',
  'Card',
  'CardSkeleton',
  'Checkbox',
  'CloseIcon',
  'ColorPicker',
  'ComboBox',
  'CommandPalette',
  'ContextMenu',
  'DataTable',
  'DesktopNavigation',
  'EmptyState',
  'Field',
  'FileDrop',
  'GlassAutoRim',
  'GlassGroup',
  'GlassPathRim',
  'GlassPathSurface',
  'GlassSurface',
  'Hint',
  'IconButton',
  'InfoPopover',
  'Kbd',
  'LinkButton',
  'LiquidGlassButton',
  'LiquidGlassSurface',
  'MenuButton',
  'MeterBar',
  'MobileNavigation',
  'NativeDateInput',
  'Notice',
  'NotificationCenter',
  'NotificationFlyout',
  'NumberInput',
  'Pagination',
  'PasswordField',
  'PerspectiveCard',
  'Presentation',
  'Progress',
  'RadioCards',
  'Range',
  'SearchInput',
  'SegmentedControl',
  'Select',
  'Separator',
  'SettingsCard',
  'Skeleton',
  'StatusDot',
  'Stepper',
  'Switch',
  'Tabs',
  'Tags',
  'TextAreaField',
  'Toast',
  'ToggleButton',
  'ToggleButtonGroup',
  'Toolbar',
  'ToolbarButton',
  'glassPathMask',
  'toastQueue',
];

const library = await import('../dist-lib/index.js');
assert.deepEqual(Object.keys(library).sort(), expected);
await Promise.all([
  access(new URL('../dist-lib/nacre.css', import.meta.url)),
  access(new URL('../dist-lib/types/index.d.ts', import.meta.url)),
]);
console.log(`verified ${expected.length} exports, CSS, and declarations`);
